### ISSUE TITLE
What is the differences of gene expression profiles between Depmap and Cancer Cell Line Encyclopedia (CCLE)

### ISSUE THREAD

**Issue by zhouxuzhouxu** [broadinstitute/depmap_omics#120]
In 2018, CCLE provided RNAseq data for 1019 cancer cell lines (https://sites.broadinstitute.org/ccle/), which also were downloaded in DepMap. However, the recent DepMap release contains the gene expression profile of  1408 cancer cell line. We observed that the expression values of the same gene in the same cell lines of depmap and CCLE are different. Thus, there are some questions that need to be consulted: Has DepMap used CCLE's RNAseq raw data (overlapped cancer cell lines between CCLE in 2018 and DepMap), just use different analysis processes ?  Whether are only specific cancer cell lines in DepMap sequenced by DepMap?

**Comment by 5im1z** [comment]
Hi,

DepMap continues to expand after the CCLE project, which is why you are seeing more cell lines now than in the CCLE paper. To answer your question, we are still using the same raw data for the CCLE lines, but have been regularly updating the data processing pipeline and reference parameters. This have resulted in some slight differences in the data.

Hope this helps,
Simone
